const mantras = [
  // * momentum
  'Accept and embrace all experiences.',
  'Act without expectation.',
  'Action expresses priorities.',
  'All is well.',
  'Be at peace.',
  'Be fearless.',
  'Be here now.',
  'Be honest.',
  'Be kind to yourself.',
  'Be kind.',
  'Be patient.',
  'Be present.',
  'Be still.',
  'Because you can.',
  'Begin.',
  'Change your thoughts, change your world.',
  'Choose joy.',
  'Create every day.',
  'Do more with less.',
  'Do the things you love.',
  'Dream big.',
  'Enjoy the present moment.',
  'Enjoy today.',
  'Every day is precious.',
  'Everything you need is within you.',
  'Express yourself.',
  'Fear less, love more.',
  'Focus on the positive.',
  'Follow your soul.',
  'Forgive yourself.',
  'Good things take time.',
  'Have patience.',
  'Help others.',
  'Illuminate the beauty in others.',
  'It’s a good day to have a good day.',
  'Let your light shine.',
  'Live fearlessly.',
  'Live simply.',
  'Live what you love.',
  'Make a difference.',
  'Mindset matters.',
  'Nature heals.',
  'Rise above.',
  'Run your own race.',
  'See the good.',
  'Smile, breathe and go slowly.',
  'Start with optimism.',
  'Stay hungry; stay foolish.',
  'Stay magical.',
  'Stay positive.',
  'Stay true.',
  'Stop all postponement.',
  'Strive for greatness.',
  'Talk less, listen more.',
  'Think big, live simply.',
  'Trust your instincts.',
  'Trust your intuition.',
  'Value yourself.',
  'Yes, you can.',
  'You are enough.',
  'You are not alone.',
  'You become what you believe.',
  'You can and you will.',
  'You matter.',
  'Your potential is unlimited.',

  // * huawei
  'The journey is hard and joyful.',

  // * steve jobs
  'Stay hungry, stay foolish',

  // * my collection
  'Always learn from the best!',
  'Environment Body Mind',
  'Fail Fast, Fail Cheap, Move On.',
  'Happy Smart Useful',
  'I hear & I forget. I see & I remember. I do & I understand.',
  'Judge less, Observe more',
  'Sic Parvis Magna',
  'Victory Loves Preparation',
];

module.exports = mantras;
